### ISSUE TITLE
apple mach-o linker (id)error

### ISSUE THREAD

**Issue by plpldog** [Coding/CodingMart_iOS#2]
![363abdc3-2c2f-46c3-a78b-dd165ed0c83e](https://user-images.githubusercontent.com/13845941/41152929-c97ac6a8-6b47-11e8-8990-3b0f4c809340.png)

**Comment by wanghengheng** [comment]
[Google](https://www.google.com.hk/search?q=apple+mach-o+linker+(id)error&oq=apple+mach-o+linker+(id)error&aqs=chrome..69i57j69i61.360j0j7&sourceid=chrome&ie=UTF-8)

[一个思路](https://www.jianshu.com/p/83824998cee2)
